{
  imports = [
    ./snacks.nix
    ./oil.nix
    ./tawny.nix
    ./lsp.nix
    ./blink-cmp.nix
    ./dashboard.nix
    ./flash.nix
    ./noice.nix
    ./treesitter.nix
    ./lualine.nix
    ./bufferline.nix
    ./nvimacs.nix
    ./autoclose.nix
    ./markview.nix
    ./gitsign.nix
    ./ts-autotag.nix
    ./vimtex.nix
    ./which-key.nix
    ./highlight-colors.nix
    ./conform-nvim.nix
    ./tiny-inline-diagnostic.nix
  ];
}
