{
  imports = [
    ./snacks.nix
    ./oil.nix
    ./tawny.nix
    ./lsp.nix
    ./blink-cmp.nix
    ./dashboard.nix
    ./flash.nix
    ./noice.nix
    ./treesitter.nix
    ./lualine.nix
    ./dropbar.nix
    ./incline.nix
    ./nvimacs.nix
    ./vimade.nix
    ./autoclose.nix
    ./scrollview.nix
    ./markview.nix
    ./gitsign.nix
    ./ts-autotag.nix
    ./vimtex.nix
    ./which-key.nix
  ];
}
